# Generated by Django 4.2.23 on 2025-10-22 16:37

import account.models
import account.vaidators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-id"],
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="آدرس ایمیل کاربر (اختیاری)",
                max_length=254,
                null=True,
                verbose_name="ایمیل",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="fullName",
            field=models.CharField(
                blank=True,
                help_text="نام و نام خانوادگی کاربر",
                max_length=255,
                verbose_name="نام کامل",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="تصویر پروفایل کاربر",
                null=True,
                upload_to=account.models.image_file_path,
                verbose_name="تصویر پروفایل",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="آیا کاربر فعال است؟", verbose_name="فعال"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="آیا کاربر دسترسی ادمین دارد؟",
                verbose_name="کارمند",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                help_text="شماره تلفن همراه کاربر",
                max_length=11,
                unique=True,
                validators=[account.vaidators.PhoneValidator()],
                verbose_name="شماره تلفن",
            ),
        ),
    ]
