# Generated by Django 4.2.23 on 2025-10-10 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="نام")),
                ("slug", models.SlugField(max_length=125, verbose_name="اسلاگ")),
            ],
            options={
                "verbose_name": "استان",
                "verbose_name_plural": "استان ها",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=85, verbose_name="نام")),
                ("slug", models.SlugField(max_length=225, verbose_name="اسلاگ")),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="province.province",
                        verbose_name="استان",
                    ),
                ),
            ],
            options={
                "verbose_name": "شهر",
                "verbose_name_plural": "شهر ها",
            },
        ),
    ]
