# Generated by Django 4.2.23 on 2025-10-10 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FestivalRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "father_name",
                    models.CharField(max_length=100, verbose_name="نام پدر"),
                ),
                (
                    "national_id",
                    models.CharField(max_length=10, unique=True, verbose_name="کد ملی"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "مرد"), ("female", "زن")],
                        max_length=10,
                        verbose_name="جنسیت",
                    ),
                ),
                ("education", models.CharField(max_length=255, verbose_name="تحصیلات")),
                (
                    "phone_number",
                    models.CharField(max_length=11, verbose_name="شماره تماس"),
                ),
                (
                    "virtual_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="شماره مجازی"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("tehran", "تهران"),
                            ("alborz", "البرز"),
                            ("isfahan", "اصفهان"),
                            ("fars", "فارس"),
                            ("khorasan_razavi", "خراسان رضوی"),
                            ("khuzestan", "خوزستان"),
                            ("azerbaijan_east", "آذربایجان شرقی"),
                            ("azerbaijan_west", "آذربایجان غربی"),
                            ("kermanshah", "کرمانشاه"),
                            ("mazandaran", "مازندران"),
                            ("markazi", "مرکزی"),
                            ("hamadan", "همدان"),
                            ("lorestan", "لرستان"),
                            ("kerman", "کرمان"),
                            ("ardabil", "اردبیل"),
                            ("kurdistan", "کردستان"),
                            ("yazd", "یزد"),
                            ("hormozgan", "هرمزگان"),
                            ("zanjan", "زنجان"),
                            ("qazvin", "قزوین"),
                            ("qom", "قم"),
                            ("golestan", "گلستان"),
                            ("khorasan_north", "خراسان شمالی"),
                            ("khorasan_south", "خراسان جنوبی"),
                            ("chaharmahal_bakhtiari", "چهارمحال و بختیاری"),
                            ("boyer_ahmad", "بویراحمد"),
                            ("ilam", "ایلام"),
                            ("bushehr", "بوشهر"),
                            ("sistan_baluchestan", "سیستان و بلوچستان"),
                            ("semnan", "سمنان"),
                            ("gilan", "گیلان"),
                        ],
                        max_length=50,
                        verbose_name="استان",
                    ),
                ),
                (
                    "media_name",
                    models.CharField(max_length=255, verbose_name="نام رسانه"),
                ),
                (
                    "festival_format",
                    models.CharField(
                        choices=[
                            ("news_report", "گزارش خبری"),
                            ("interview", "مصاحبه"),
                            ("editorial", "یادداشت و سرمقاله"),
                            ("headline", "تیتر"),
                            ("infographic", "اینفوگرافی"),
                            ("motion_graphic", "موشن گرافی"),
                            ("photo", "عکس"),
                            ("video_clip", "کلیپ و گزارش ویدیویی"),
                            ("documentary", "مستند"),
                            ("podcast", "پادکست"),
                        ],
                        max_length=50,
                        verbose_name="قالب جشنواره",
                    ),
                ),
                (
                    "festival_topic",
                    models.CharField(
                        choices=[
                            ("year_slogan", "شعار سال"),
                            ("jihad_explanation", "جهاد تبیین"),
                            ("media_industry", "پیوند رسانه و صنعت"),
                            ("social_harms", "مقابله با آسیب\u200cهای اجتماعی"),
                            ("revolution_achievements", "دستاوردهای انقلاب اسلامی"),
                            ("basij_action", "بسیج و حوزه\u200cهای اقدام"),
                            ("hope_happiness", "امید و نشاط آفرینی"),
                            ("family_society", "خانواده ،جامعه و فرزندآوری"),
                            ("islamic_lifestyle", "سبک زندگی ایرانی اسلامی"),
                            ("sacrifice_martyrdom", "ایثار و شهادت"),
                            (
                                "water_electricity_saving",
                                "صرفه\u200cجویی در مصرف آب و برق",
                            ),
                        ],
                        max_length=50,
                        verbose_name="محور جشنواره",
                    ),
                ),
                (
                    "special_section",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("progress_narrative", "روایت پیشرفت"),
                            ("field_narrative_12days", "روایت میدان در جنگ ۱۲ روزه"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="بخش ویژه",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="festival_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ثبت نام جشنواره",
                "verbose_name_plural": "ثبت نام های جشنواره",
                "ordering": ["-created_at"],
            },
        ),
    ]
