# Generated by Django 4.2.23 on 2025-10-10 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("province", "0001_initial"),
        ("festival", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="festivalregistration",
            name="city",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="province.city",
                verbose_name="شهر",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="festivalregistration",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="province.province",
                verbose_name="استان",
            ),
        ),
    ]
