# Generated by Django 4.2.23 on 2025-10-13 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0002_festivalregistration_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="عنوان اثر", max_length=255, verbose_name="عنوان"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="توضیحات کامل در مورد اثر", verbose_name="توضیحات"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="فایل مربوط به اثر",
                        null=True,
                        upload_to="festival/works/",
                        verbose_name="فایل",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
                (
                    "festival_registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="works",
                        to="festival.festivalregistration",
                        verbose_name="ثبت نام جشنواره",
                    ),
                ),
            ],
            options={
                "verbose_name": "اثر",
                "verbose_name_plural": "آثار",
                "ordering": ["-created_at"],
            },
        ),
    ]
