# Generated by Django 4.2.23 on 2025-10-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0003_work"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="file",
            field=models.FileField(
                default="test",
                help_text="فایل مربوط به اثر (حداکثر ۱۱۰ مگابایت)",
                upload_to="festival/works/",
                verbose_name="فایل",
            ),
            preserve_default=False,
        ),
    ]
