# Generated by Django 4.2.23 on 2025-10-13 11:56

from django.db import migrations, models
import festival.models.work


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0004_alter_work_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="file",
            field=models.FileField(
                help_text="فایل مربوط به اثر (حداکثر ۱۱۰ مگابایت)",
                upload_to=festival.models.work.work_file_upload_path,
                verbose_name="فایل",
            ),
        ),
    ]
