# Generated by Django 4.2.23 on 2025-10-22 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0005_alter_work_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="FestivalFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="کد یکتای قالب (انگلیسی)",
                        max_length=50,
                        unique=True,
                        verbose_name="کد قالب",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="نام فارسی قالب",
                        max_length=200,
                        verbose_name="نام قالب",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="توضیحات تکمیلی درباره این قالب",
                        null=True,
                        verbose_name="توضیحات",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="آیا این قالب فعال است؟",
                        verbose_name="فعال",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="ترتیب نمایش در لیست\u200cها",
                        verbose_name="ترتیب نمایش",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "قالب جشنواره",
                "verbose_name_plural": "قالب\u200cهای جشنواره",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FestivalSpecialSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="کد یکتای بخش (انگلیسی)",
                        max_length=50,
                        unique=True,
                        verbose_name="کد بخش",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="نام فارسی بخش ویژه",
                        max_length=200,
                        verbose_name="نام بخش",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="توضیحات تکمیلی درباره این بخش",
                        null=True,
                        verbose_name="توضیحات",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="آیا این بخش فعال است؟",
                        verbose_name="فعال",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="ترتیب نمایش در لیست\u200cها",
                        verbose_name="ترتیب نمایش",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "بخش ویژه جشنواره",
                "verbose_name_plural": "بخش\u200cهای ویژه جشنواره",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FestivalTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="کد یکتای محور (انگلیسی)",
                        max_length=50,
                        unique=True,
                        verbose_name="کد محور",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="نام فارسی محور",
                        max_length=200,
                        verbose_name="نام محور",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="توضیحات تکمیلی درباره این محور",
                        null=True,
                        verbose_name="توضیحات",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="آیا این محور فعال است؟",
                        verbose_name="فعال",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="ترتیب نمایش در لیست\u200cها",
                        verbose_name="ترتیب نمایش",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "محور جشنواره",
                "verbose_name_plural": "محورهای جشنواره",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="festivalregistration",
            name="national_id",
            field=models.CharField(max_length=10, verbose_name="کد ملی"),
        ),
        # Step 1: Rename old fields to keep the data
        migrations.RenameField(
            model_name='festivalregistration',
            old_name='festival_format',
            new_name='festival_format_old',
        ),
        migrations.RenameField(
            model_name='festivalregistration',
            old_name='festival_topic',
            new_name='festival_topic_old',
        ),
        migrations.RenameField(
            model_name='festivalregistration',
            old_name='special_section',
            new_name='special_section_old',
        ),
        # Step 2: Add new ForeignKey fields (nullable for migration)
        migrations.AddField(
            model_name='festivalregistration',
            name='festival_format',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='registrations',
                to='festival.festivalformat',
                verbose_name='قالب جشنواره',
            ),
        ),
        migrations.AddField(
            model_name='festivalregistration',
            name='festival_topic',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='registrations',
                to='festival.festivaltopic',
                verbose_name='محور جشنواره',
            ),
        ),
        migrations.AddField(
            model_name='festivalregistration',
            name='special_section',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='registrations',
                to='festival.festivalspecialsection',
                verbose_name='بخش ویژه',
            ),
        ),
    ]
