# Generated by Django 4.2.23 on 2025-10-22 15:17

from django.db import migrations


def populate_festival_categories(apps, schema_editor):
    """Populate festival category tables with initial data and migrate existing registrations"""
    FestivalFormat = apps.get_model("festival", "FestivalFormat")
    FestivalTopic = apps.get_model("festival", "FestivalTopic")
    FestivalSpecialSection = apps.get_model("festival", "FestivalSpecialSection")
    FestivalRegistration = apps.get_model("festival", "FestivalRegistration")

    # Populate Festival Formats
    formats = [
        ("news_report", "گزارش خبری"),
        ("interview", "مصاحبه"),
        ("editorial", "یادداشت و سرمقاله"),
        ("headline", "تیتر"),
        ("infographic", "اینفوگرافی"),
        ("motion_graphic", "موشن گرافی"),
        ("photo", "عکس"),
        ("video_clip", "کلیپ و گزارش ویدیویی"),
        ("documentary", "مستند"),
        ("podcast", "پادکست"),
    ]

    for code, name in formats:
        FestivalFormat.objects.get_or_create(
            code=code, defaults={"name": name, "is_active": True}
        )

    # Populate Festival Topics
    topics = [
        ("year_slogan", "شعار سال"),
        ("jihad_explanation", "جهاد تبیین"),
        ("media_industry", "پیوند رسانه و صنعت"),
        ("social_harms", "مقابله با آسیب‌های اجتماعی"),
        ("revolution_achievements", "دستاوردهای انقلاب اسلامی"),
        ("basij_action", "بسیج و حوزه‌های اقدام"),
        ("hope_happiness", "امید و نشاط آفرینی"),
        ("family_society", "خانواده ،جامعه و فرزندآوری"),
        ("islamic_lifestyle", "سبک زندگی ایرانی اسلامی"),
        ("sacrifice_martyrdom", "ایثار و شهادت"),
        ("water_electricity_saving", "صرفه‌جویی در مصرف آب و برق"),
    ]

    for code, name in topics:
        FestivalTopic.objects.get_or_create(
            code=code, defaults={"name": name, "is_active": True}
        )

    # Populate Festival Special Sections
    sections = [
        ("progress_narrative", "روایت پیشرفت"),
        ("field_narrative_12days", "روایت میدان در جنگ ۱۲ روزه"),
    ]

    for code, name in sections:
        FestivalSpecialSection.objects.get_or_create(
            code=code, defaults={"name": name, "is_active": True}
        )
    
    # Migrate existing data from old fields to new ForeignKey fields
    for registration in FestivalRegistration.objects.all():
        # Migrate festival_format
        if hasattr(registration, 'festival_format_old') and registration.festival_format_old:
            try:
                festival_format = FestivalFormat.objects.get(code=registration.festival_format_old)
                registration.festival_format = festival_format
            except FestivalFormat.DoesNotExist:
                pass  # Skip if code doesn't exist
        
        # Migrate festival_topic
        if hasattr(registration, 'festival_topic_old') and registration.festival_topic_old:
            try:
                festival_topic = FestivalTopic.objects.get(code=registration.festival_topic_old)
                registration.festival_topic = festival_topic
            except FestivalTopic.DoesNotExist:
                pass
        
        # Migrate special_section
        if hasattr(registration, 'special_section_old') and registration.special_section_old:
            try:
                special_section = FestivalSpecialSection.objects.get(code=registration.special_section_old)
                registration.special_section = special_section
            except FestivalSpecialSection.DoesNotExist:
                pass
        
        registration.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "festival",
            "0006_festivalformat_festivalspecialsection_festivaltopic_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            populate_festival_categories, reverse_code=migrations.RunPython.noop
        ),
    ]
