# Generated by Django 4.2.23 on 2025-10-22 15:17

from django.db import migrations


def populate_festival_categories(apps, schema_editor):
    """Populate festival category tables with initial data"""
    FestivalFormat = apps.get_model("festival", "FestivalFormat")
    FestivalTopic = apps.get_model("festival", "FestivalTopic")
    FestivalSpecialSection = apps.get_model("festival", "FestivalSpecialSection")

    # Populate Festival Formats
    formats = [
        ("news_report", "گزارش خبری"),
        ("interview", "مصاحبه"),
        ("editorial", "یادداشت و سرمقاله"),
        ("headline", "تیتر"),
        ("infographic", "اینفوگرافی"),
        ("motion_graphic", "موشن گرافی"),
        ("photo", "عکس"),
        ("video_clip", "کلیپ و گزارش ویدیویی"),
        ("documentary", "مستند"),
        ("podcast", "پادکست"),
    ]

    for code, name in formats:
        FestivalFormat.objects.get_or_create(
            code=code, defaults={"name": name, "is_active": True}
        )

    # Populate Festival Topics
    topics = [
        ("year_slogan", "شعار سال"),
        ("jihad_explanation", "جهاد تبیین"),
        ("media_industry", "پیوند رسانه و صنعت"),
        ("social_harms", "مقابله با آسیب‌های اجتماعی"),
        ("revolution_achievements", "دستاوردهای انقلاب اسلامی"),
        ("basij_action", "بسیج و حوزه‌های اقدام"),
        ("hope_happiness", "امید و نشاط آفرینی"),
        ("family_society", "خانواده ،جامعه و فرزندآوری"),
        ("islamic_lifestyle", "سبک زندگی ایرانی اسلامی"),
        ("sacrifice_martyrdom", "ایثار و شهادت"),
        ("water_electricity_saving", "صرفه‌جویی در مصرف آب و برق"),
    ]

    for code, name in topics:
        FestivalTopic.objects.get_or_create(
            code=code, defaults={"name": name, "is_active": True}
        )

    # Populate Festival Special Sections
    sections = [
        ("progress_narrative", "روایت پیشرفت"),
        ("field_narrative_12days", "روایت میدان در جنگ ۱۲ روزه"),
    ]

    for code, name in sections:
        FestivalSpecialSection.objects.get_or_create(
            code=code, defaults={"name": name, "is_active": True}
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "festival",
            "0006_festivalformat_festivalspecialsection_festivaltopic_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            populate_festival_categories, reverse_code=migrations.RunPython.noop
        ),
    ]
