# Generated by Django 4.2.23 on 2025-10-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0008_remove_old_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="publish_link",
            field=models.URLField(
                blank=True,
                help_text="لینک اثر منتشر شده (اختیاری)",
                max_length=500,
                null=True,
                verbose_name="لینک انتشار",
            ),
        ),
    ]
