# Generated by Django 4.2.23 on 2025-10-10 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="codelog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "لاگ سیستم",
                "verbose_name_plural": "لاگ\u200cهای سیستم",
            },
        ),
        migrations.AddField(
            model_name="codelog",
            name="exception_message",
            field=models.TextField(
                blank=True,
                help_text="پیام خطای استثنا",
                null=True,
                verbose_name="پیام استثنا",
            ),
        ),
        migrations.AddField(
            model_name="codelog",
            name="exception_type",
            field=models.CharField(
                blank=True,
                help_text="نوع استثنای رخ داده",
                max_length=100,
                null=True,
                verbose_name="نوع استثنا",
            ),
        ),
        migrations.AddField(
            model_name="codelog",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, help_text="آدرس IP کاربر", null=True, verbose_name="آدرس IP"
            ),
        ),
        migrations.AddField(
            model_name="codelog",
            name="is_resolved",
            field=models.BooleanField(
                default=False,
                help_text="آیا این مسئله حل شده است؟",
                verbose_name="حل شده",
            ),
        ),
        migrations.AddField(
            model_name="codelog",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("SYSTEM", "سیستم"),
                    ("USER_ACTION", "عملیات کاربر"),
                    ("API_CALL", "فراخوانی API"),
                    ("DATABASE", "پایگاه داده"),
                    ("AUTHENTICATION", "احراز هویت"),
                    ("AUTHORIZATION", "مجوز دسترسی"),
                    ("VALIDATION", "اعتبارسنجی"),
                    ("EXCEPTION", "استثنا"),
                    ("PERFORMANCE", "عملکرد"),
                    ("SECURITY", "امنیت"),
                ],
                default="SYSTEM",
                help_text="دسته\u200cبندی نوع لاگ",
                max_length=20,
                verbose_name="نوع لاگ",
            ),
        ),
        migrations.AddField(
            model_name="codelog",
            name="request_method",
            field=models.CharField(
                blank=True,
                help_text="نوع HTTP method (GET, POST, etc.)",
                max_length=10,
                null=True,
                verbose_name="روش درخواست",
            ),
        ),
        migrations.AddField(
            model_name="codelog",
            name="request_path",
            field=models.CharField(
                blank=True,
                help_text="مسیر URL درخواست",
                max_length=500,
                null=True,
                verbose_name="مسیر درخواست",
            ),
        ),
        migrations.AddField(
            model_name="codelog",
            name="resolution_note",
            field=models.TextField(
                blank=True,
                help_text="توضیحات مربوط به حل مسئله",
                null=True,
                verbose_name="یادداشت حل مسئله",
            ),
        ),
        migrations.AddField(
            model_name="codelog",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="برچسب\u200cهای مفید برای جستجو (با کاما جدا کنید)",
                max_length=200,
                null=True,
                verbose_name="برچسب\u200cها",
            ),
        ),
        migrations.AddField(
            model_name="codelog",
            name="traceback_info",
            field=models.TextField(
                blank=True,
                help_text="اطلاعات کامل traceback",
                null=True,
                verbose_name="جزئیات traceback",
            ),
        ),
        migrations.AddField(
            model_name="codelog",
            name="user_agent",
            field=models.TextField(
                blank=True,
                help_text="اطلاعات مرورگر کاربر",
                null=True,
                verbose_name="User Agent",
            ),
        ),
        migrations.AlterField(
            model_name="codelog",
            name="context",
            field=models.JSONField(
                blank=True,
                help_text="اطلاعات اضافی (پارامترها، وضعیت، و غیره)",
                null=True,
                verbose_name="زمینه",
            ),
        ),
        migrations.AlterField(
            model_name="codelog",
            name="cpu_usage",
            field=models.FloatField(
                blank=True,
                help_text="درصد مصرف پردازنده",
                null=True,
                verbose_name="مصرف CPU",
            ),
        ),
        migrations.AlterField(
            model_name="codelog",
            name="duration",
            field=models.FloatField(
                blank=True,
                help_text="زمان اجرا به ثانیه",
                null=True,
                verbose_name="مدت اجرا",
            ),
        ),
        migrations.AlterField(
            model_name="codelog",
            name="level",
            field=models.CharField(
                choices=[
                    ("DEBUG", "اشکال\u200cزدایی"),
                    ("INFO", "اطلاعات"),
                    ("WARNING", "هشدار"),
                    ("ERROR", "خطا"),
                    ("CRITICAL", "خطای بحرانی"),
                    ("ACTION_LOG", "لاگ عملیات"),
                    ("EXCEPTION", "استثنا"),
                    ("SECURITY", "امنیتی"),
                    ("PERFORMANCE", "عملکرد"),
                ],
                default="INFO",
                help_text="سطح اهمیت لاگ",
                max_length=15,
                verbose_name="سطح لاگ",
            ),
        ),
        migrations.AlterField(
            model_name="codelog",
            name="memory_usage",
            field=models.FloatField(
                blank=True,
                help_text="درصد مصرف حافظه",
                null=True,
                verbose_name="مصرف حافظه",
            ),
        ),
        migrations.AlterField(
            model_name="codelog",
            name="message",
            field=models.TextField(help_text="متن پیام لاگ", verbose_name="پیام"),
        ),
        migrations.AlterField(
            model_name="codelog",
            name="method",
            field=models.CharField(
                blank=True,
                help_text="نام متد یا تابع",
                max_length=100,
                verbose_name="متد",
            ),
        ),
        migrations.AlterField(
            model_name="codelog",
            name="module",
            field=models.CharField(
                help_text="نام ماژول یا فایل مبدأ لاگ",
                max_length=100,
                verbose_name="ماژول",
            ),
        ),
        migrations.AlterField(
            model_name="codelog",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, help_text="زمان ثبت لاگ", verbose_name="زمان ثبت"
            ),
        ),
        migrations.AlterField(
            model_name="codelog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="کاربر مرتبط با این لاگ",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AddIndex(
            model_name="codelog",
            index=models.Index(
                fields=["log_type"], name="monitoring__log_typ_8676a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codelog",
            index=models.Index(fields=["user"], name="monitoring__user_id_e614c9_idx"),
        ),
        migrations.AddIndex(
            model_name="codelog",
            index=models.Index(
                fields=["exception_type"], name="monitoring__excepti_27f7a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codelog",
            index=models.Index(
                fields=["is_resolved"], name="monitoring__is_reso_365d5c_idx"
            ),
        ),
    ]
