# Generated by Django 4.2.23 on 2025-10-12 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="نام و نام خانوادگی کامل",
                        max_length=100,
                        verbose_name="نام کامل",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="شماره موبایل (مثال: 09123456789)",
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="شماره تلفن باید به فرم 09XXXXXXXXX باشد",
                                regex="^09\\d{9}$",
                            )
                        ],
                        verbose_name="شماره تلفن",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="آدرس ایمیل معتبر",
                        max_length=254,
                        verbose_name="ایمیل",
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="متن پیام شما", verbose_name="پیام"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "پیام تماس",
                "verbose_name_plural": "پیام\u200cهای تماس",
                "ordering": ["-created_at"],
            },
        ),
    ]
