# Generated by Django 4.2.23 on 2025-10-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="عنوان بخش درباره ما",
                        max_length=200,
                        verbose_name="عنوان",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="متن کامل درباره ما", verbose_name="محتوا"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="تصویر مرتبط با بخش درباره ما",
                        null=True,
                        upload_to="info/about/",
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="آیا این بخش فعال است؟",
                        verbose_name="فعال",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="ترتیب نمایش (عدد کمتر اولویت بیشتر)",
                        verbose_name="ترتیب",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "درباره ما",
                "verbose_name_plural": "درباره ما",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.CharField(
                        help_text="متن سوال", max_length=300, verbose_name="سوال"
                    ),
                ),
                ("answer", models.TextField(help_text="متن پاسخ", verbose_name="پاسخ")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="آیا این سوال فعال است؟",
                        verbose_name="فعال",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="ترتیب نمایش (عدد کمتر اولویت بیشتر)",
                        verbose_name="ترتیب",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "سوال متداول",
                "verbose_name_plural": "سوالات متداول",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
