# Generated by Django 4.2.23 on 2025-10-22 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0002_aboutus_faq"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AboutUs",
        ),
        migrations.DeleteModel(
            name="FAQ",
        ),
    ]
