# Generated by Django 4.2.23 on 2025-10-10 16:32

from django.db import migrations, models
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="عنوان محتوا", max_length=200, verbose_name="عنوان"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="توضیحات کامل محتوا", verbose_name="توضیحات"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="تصویر مرتبط با محتوا",
                        null=True,
                        upload_to="content/images/",
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "publish_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="تاریخ انتشار محتوا",
                        verbose_name="تاریخ انتشار",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="برچسب\u200cهای مرتبط با محتوا",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="برچسب\u200cها",
                    ),
                ),
            ],
            options={
                "verbose_name": "خبر",
                "verbose_name_plural": "اخبار",
                "ordering": ["-publish_date"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="عنوان محتوا", max_length=200, verbose_name="عنوان"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="توضیحات کامل محتوا", verbose_name="توضیحات"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="تصویر مرتبط با محتوا",
                        null=True,
                        upload_to="content/images/",
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "publish_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="تاریخ انتشار محتوا",
                        verbose_name="تاریخ انتشار",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="برچسب\u200cهای مرتبط با محتوا",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="برچسب\u200cها",
                    ),
                ),
            ],
            options={
                "verbose_name": "رویداد",
                "verbose_name_plural": "رویدادها",
                "ordering": ["-publish_date"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="عنوان محتوا", max_length=200, verbose_name="عنوان"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="توضیحات کامل محتوا", verbose_name="توضیحات"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="تصویر مرتبط با محتوا",
                        null=True,
                        upload_to="content/images/",
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "publish_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="تاریخ انتشار محتوا",
                        verbose_name="تاریخ انتشار",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="برچسب\u200cهای مرتبط با محتوا",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="برچسب\u200cها",
                    ),
                ),
            ],
            options={
                "verbose_name": "آموزش",
                "verbose_name_plural": "آموزش\u200cها",
                "ordering": ["-publish_date"],
            },
        ),
    ]
