# Generated by Django 4.2.23 on 2025-10-12 11:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="description",
            field=ckeditor.fields.RichTextField(
                help_text="توضیحات کامل محتوا", verbose_name="توضیحات"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=ckeditor.fields.RichTextField(
                help_text="توضیحات کامل محتوا", verbose_name="توضیحات"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="description",
            field=ckeditor.fields.RichTextField(
                help_text="توضیحات کامل محتوا", verbose_name="توضیحات"
            ),
        ),
    ]
