# Generated by Django 4.2.23 on 2025-10-22 15:37

import content.models.education
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content",
            "0002_alter_education_description_alter_event_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="document",
            field=models.FileField(
                blank=True,
                help_text="فایل آموزشی PDF یا PowerPoint (فرمت\u200cهای مجاز: pdf, ppt, pptx - حداکثر 50 مگابایت)",
                null=True,
                upload_to=content.models.education.education_document_upload_path,
                verbose_name="فایل آموزشی",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="فایل ویدیوی آموزشی (فرمت\u200cهای مجاز: mp4, avi, mov, mkv, wmv - حداکثر 500 مگابایت)",
                null=True,
                upload_to=content.models.education.education_video_upload_path,
                verbose_name="ویدیو آموزشی",
            ),
        ),
    ]
