# Generated by Django 4.2.23 on 2025-10-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_education_document_education_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="تعداد دفعاتی که این محتوا مشاهده شده است",
                verbose_name="تعداد بازدید",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="تعداد دفعاتی که این محتوا مشاهده شده است",
                verbose_name="تعداد بازدید",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="تعداد دفعاتی که این محتوا مشاهده شده است",
                verbose_name="تعداد بازدید",
            ),
        ),
    ]
